const SIGNIN = {
    SIGNIN_LOAD: 'SIGNIN_LOAD',
    SIGNIN_LOAD_SUCCESS: 'SIGNIN_LOAD_SUCCESS',
    SIGNIN_LOAD_FAIL: 'SIGNIN_LOAD_FAIL'
}

const SIGNUP = {
    SIGNUP_LOAD: 'SIGNUP_LOAD',
    SIGNUP_LOAD_SUCCESS: 'SIGNUP_LOAD_SUCCESS',
    SIGNUP_LOAD_FAIL: 'SIGNUP_LOAD_FAIL'
}

const CREATEPOST = {
    CREATEPOST_LOAD: 'CREATEPOST_LOAD',
    CREATEPOST_LOAD_SUCCESS: 'CREATEPOST_LOAD_SUCCESS',
    CREATEPOST_LOAD_FAIL: 'CREATEPOST_LOAD_FAIL'
}
const SOCIAL = {
    SOCIAL_LOAD: 'SOCIAL_LOAD',
    SOCIAL_LOAD_SUCCESS: 'SOCIAL_LOAD_SUCCESS',
    SOCIAL_LOAD_FAIL: 'SOCIAL_LOAD_FAIL'
}

export { SIGNIN,SIGNUP,CREATEPOST,SOCIAL }